---
title: "ABA_Hackathon"
author: "Danya Zhang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(magrittr)
```

# Data Cleaning
```{r}
# read in the data
insurance <- read.csv("Medical Insurance dataset.csv")
```

```{r}
# check for null values
colSums(is.na(insurance)) # no nulls
```

```{r}
# new data set with altered variables ready for eda
insurance_clean <- insurance
insurance_clean$female <- ifelse(insurance$sex == "female", 1, 0) # binary var
insurance_clean$smoker <- ifelse(insurance$smoker == "yes", 1, 0) 
insurance_clean$region <- factor(insurance_clean$region)
insurance_clean %<>% 
  select(-sex)


insurance_clean <- insurance_clean %>%
  mutate(
  region = case_when(
  region == "northeast" ~ "NE",
  region == "northwest" ~ "NW",
  region == "southeast" ~ "SE",
  region == "southwest" ~ "SW",
    TRUE ~ region  
))

insurance_clean$region <- factor(insurance_clean$region)
```

```{r}
ggplot(insurance_clean, aes(x = age, y = charges)) + 
  geom_point() +
    labs(title = "Charges vs. Age", x = "Age", y = "Charges")

ggplot(insurance_clean, aes(x = bmi, y = charges)) + 
  geom_point() +
  labs(title = "Charges vs. BMI", x = "BMI", y = "Charges") +
  geom_smooth()
```


